---
- name: Add GitHub CLI GPG key and repository
  become: true
  shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/github-cli.list

- name: Install GitHub CLI
  become: true
  apt:
    name: gh
    state: present
    update_cache: yes
