---
- name: Add HashiCorp GPG key and repository
  become: true
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/hashicorp.list

- name: Install Terraform
  become: true
  apt:
    name: terraform
    state: present
    update_cache: yes
